draw_config:
  shrink_wide_legends: 10
  svg_extra_style: |
    text.label, text.footer {
        stroke: none;
        fill: #24292e;
    }
    @media (prefers-color-scheme: dark) {
        text.label, text.footer {
            fill: #c9d1d9;
        }
    }
